<template>
  <q-page class="page">
    <div class="top"><div><span>MY FOLDER</span><h1>Quiz Programmes</h1><p>Only programmes created by your account appear here.</p></div><q-btn unelevated no-caps icon="add" label="Create new quiz" to="/teacher/quizzes/new" class="create" /></div>
    <div v-if="loading" class="state"><q-spinner color="primary" size="42px" /></div>
    <div v-else-if="!quiz.programmes.length" class="empty"><q-icon name="folder_open" /><h2>No quiz programmes yet</h2><p>Create your first programme and add teams and questions.</p><q-btn unelevated no-caps label="Create quiz programme" to="/teacher/quizzes/new" class="create" /></div>
    <div v-else class="grid"><q-card v-for="item in quiz.programmes" :key="item.id" class="card"><q-card-section><div class="card-top"><q-icon name="quiz" /><q-btn flat round dense icon="more_vert"><q-menu><q-list><q-item clickable :to="`/teacher/quizzes/${item.id}/edit`" v-close-popup><q-item-section>Edit</q-item-section></q-item><q-item clickable @click="openDeleteDialog(item)" v-close-popup><q-item-section class="text-negative">Delete</q-item-section></q-item></q-list></q-menu></q-btn></div><h2>{{ item.title }}</h2><p>Last updated {{ format(item.updatedAt) }}</p><div class="actions"><q-btn unelevated no-caps icon="play_arrow" label="Open quiz" :to="`/teacher/quizzes/${item.id}/play`" /><q-btn flat no-caps label="Edit" :to="`/teacher/quizzes/${item.id}/edit`" /></div></q-card-section></q-card></div>
    <q-dialog v-model="deleteDialog" persistent><q-card class="delete-card"><q-card-section class="delete-heading"><q-icon name="warning" /><div><h2>Delete quiz programme?</h2><p>This permanently deletes the quiz and all uploaded images.</p></div></q-card-section><q-card-section><p>To delete <b>{{ selected?.title }}</b>, type <b>DELETE</b> below.</p><q-input v-model="deleteText" outlined autofocus label="Type DELETE" @keyup.enter="confirmDelete" /></q-card-section><q-card-actions align="right"><q-btn flat no-caps label="Cancel" @click="closeDeleteDialog" /><q-btn unelevated no-caps color="negative" label="Delete permanently" :disable="deleteText !== 'DELETE'" :loading="deleting" @click="confirmDelete" /></q-card-actions></q-card></q-dialog>
  </q-page>
</template>
<script setup>
import { onMounted, ref } from 'vue'
import { useQuasar } from 'quasar'
import { useQuizStore } from 'src/stores/quiz-store'
const quiz=useQuizStore(),$q=useQuasar(),loading=ref(true),deleting=ref(false),deleteDialog=ref(false),deleteText=ref(''),selected=ref(null)
const format=value=>new Date(value).toLocaleDateString()
onMounted(async()=>{try{await quiz.list()}finally{loading.value=false}})
const openDeleteDialog=item=>{selected.value=item;deleteText.value='';deleteDialog.value=true}
const closeDeleteDialog=()=>{if(!deleting.value){deleteDialog.value=false;selected.value=null;deleteText.value=''}}
const confirmDelete=async()=>{if(deleteText.value!=='DELETE'||!selected.value||deleting.value)return;deleting.value=true;try{await quiz.remove(selected.value.id);await quiz.list();$q.notify({type:'positive',message:'Quiz programme deleted'});deleteDialog.value=false;selected.value=null;deleteText.value=''}catch(error){$q.notify({type:'negative',message:error.response?.data?.message||'Quiz programme could not be deleted'})}finally{deleting.value=false}}
</script>
<style scoped>
.page{padding:42px clamp(18px,5vw,68px)}.top{display:flex;align-items:end;justify-content:space-between;gap:20px}.top span{color:#4770dc;font-size:.68rem;font-weight:900;letter-spacing:.12em}.top h1{margin:6px 0;font-size:2.15rem}.top p,.card p,.empty p{color:#8190a7}.create,.actions .q-btn:first-child{color:#fff;background:linear-gradient(110deg,#1677ff,#6745e8);border-radius:12px}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:20px;margin-top:35px}.card{border:1px solid #e0e9f5;border-radius:21px;box-shadow:0 12px 30px rgba(20,52,108,.07)}.card .q-card__section{padding:24px}.card-top{display:flex;justify-content:space-between;color:#3476e4;font-size:36px}.card h2{margin:16px 0 4px;font-size:1.2rem}.actions{display:flex;gap:8px;margin-top:23px}.empty,.state{min-height:390px;display:grid;place-content:center;justify-items:center;text-align:center}.empty>.q-icon{font-size:70px;color:#b8c8df}.empty h2{margin:12px 0 0}.delete-card{width:min(500px,calc(100vw - 28px));padding:10px;border-radius:22px}.delete-heading{display:flex;align-items:center;gap:14px}.delete-heading>.q-icon{padding:12px;color:#d6324e;background:#fff0f2;border-radius:13px;font-size:28px}.delete-heading h2{margin:0;font-size:1.25rem}.delete-heading p{margin:4px 0 0;color:#7b8ba2}.delete-card .q-card__actions{padding:12px 16px 18px}
</style>
